# Change these first
owner: eustasy # Your GitHub organization or username, where this repository lives
repo: .uptime # The name of this repository

sites:
  - name: Ashrise A1
    url: https://ashrise.com
  - name: Ashrise P2
    url: https://ashrise.com/phoenix/scrape
  - name: Ashrise MP
    url: https://ashrise.com/torrents
  - name: elementary DL-CDN Amsterdam
    url: https://ams3.dl.elementary.io/
  - name: elementary DL-CDN Frankfurt
    url: https://fra1.dl.elementary.io/
  - name: elementary DL-CDN New York City
    url: https://nyc3.dl.elementary.io/
  - name: elementary DL-CDN San Francisco
    url: https://sfo1.dl.elementary.io/
  - name: elementary DL-CDN Singapore
    url: https://sgp1.dl.elementary.io/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
